default_stages: [pre-commit, pre-merge-commit]
fail_fast: true
repos:
  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.7.3
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: pretty-format-json
        args: [--autofix, --indent, "4"]
        exclude: .*.ipynb
      - id: trailing-whitespace
        exclude: tests/fixtures/output/haplogroups\..*\.txt|data/variants/isogg\.[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.txt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: [--ignore-words-list, "astroid"]
  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.13.0
    hooks:
      - id: mypy
